# Generated by Django 5.1.2 on 2024-11-04 17:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('contact_info', models.CharField(max_length=255)),
                ('current_cohort', models.CharField(max_length=50)),
                ('current_sub_stage', models.CharField(max_length=50)),
                ('days_since_follow_up', models.IntegerField(default=0)),
                ('days_since_last_contact', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='PatientHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('previous_cohort', models.CharField(max_length=50)),
                ('previous_sub_stage', models.CharField(max_length=50)),
                ('next_cohort', models.CharField(max_length=50)),
                ('next_sub_stage', models.CharField(max_length=50)),
                ('transition_date', models.DateTimeField(auto_now_add=True)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patients.patient')),
            ],
        ),
    ]
