# Generated by Django 5.1.2 on 2024-11-04 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='age',
        ),
        migrations.RemoveField(
            model_name='patient',
            name='contact_info',
        ),
        migrations.AddField(
            model_name='patient',
            name='admission_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='admission_status',
            field=models.CharField(choices=[('Postponed', 'Postponed'), ('Cancelled', 'Cancelled')], default='Postponed', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinical_intervention_completed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='clinical_intervention_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='final_response_received',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='follow_up_attempts',
            field=models.CharField(default='None', max_length=50),
        ),
        migrations.AddField(
            model_name='patient',
            name='lead_management_ends',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='patient_ready',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='previous_cohort',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='previous_sub_stage',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='patient',
            name='quotation_accepted',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='quotation_phase_required',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='scheduled_admission',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='patient',
            name='scheduled_date_in_past',
            field=models.BooleanField(default=False),
        ),
    ]
