# Generated by Django 5.1.3 on 2024-11-09 18:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0003_patient_days_until_admission_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='followupstage',
            name='cohort_a_specific_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='newrecommendationsstage',
            name='cohort_a_specific_field',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
