# Generated by Django 5.1.3 on 2024-11-09 19:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0004_followupstage_cohort_a_specific_field_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followupstage',
            name='cohort_a_specific_field',
        ),
        migrations.RemoveField(
            model_name='newrecommendationsstage',
            name='cohort_a_specific_field',
        ),
    ]
