# Generated by Django 5.1.3 on 2024-11-12 00:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patients', '0005_remove_followupstage_cohort_a_specific_field_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='admission_status',
            field=models.CharField(choices=[('Postponed', 'Postponed'), ('Cancelled', 'Cancelled'), ('Pending', 'Pending')], default='Postponed', max_length=50),
        ),
    ]
